#!/bin/bash

echo "🔧 Setting Up WhatsApp Webhook (Without ngrok)"
echo "=============================================="
echo ""
echo "Since ngrok isn't installed, here are your options:"
echo ""
echo "📌 OPTION 1: Use Cloudflare Tunnel (Recommended - Free, No account needed)"
echo "---"
echo "Install:"
echo "  wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb"
echo "  sudo dpkg -i cloudflared-linux-amd64.deb"
echo ""
echo "Run:"
echo "  cloudflared tunnel --url http://localhost:5000"
echo ""
echo "Copy the HTTPS URL and add /api/whatsapp/webhook to the end"
echo ""
echo "=============================================="
echo ""
echo "📌 OPTION 2: Install ngrok (Recommended for testing)"
echo "---"
echo "Visit: https://ngrok.com/download"
echo "Download: Linux 64-bit"
echo ""
echo "Quick install:"
echo "  cd ~/Downloads"
echo "  wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz"
echo "  tar xzf ngrok-v3-stable-linux-amd64.tgz"
echo "  sudo mv ngrok /usr/local/bin/"
echo "  ngrok http 5000"
echo ""
echo "=============================================="
echo ""
echo "📌 OPTION 3: Use LocalTunnel (Simplest - No install)"
echo "---"
echo "npm install -g localtunnel"
echo "lt --port 5000"
echo ""
echo "=============================================="
echo ""
echo "⚡ QUICK START (LocalTunnel):"
echo ""

# Try localtunnel
if command -v lt &> /dev/null; then
    echo "✅ LocalTunnel already installed!"
    echo "Starting tunnel..."
    lt --port 5000 &
    TUNNEL_PID=$!
    sleep 3
    echo ""
    echo "Check the URL above, then:"
else
    echo "Installing LocalTunnel..."
    sudo npm install -g localtunnel
    echo ""
    echo "Now run: lt --port 5000"
fi

echo ""
echo "=============================================="
echo "📋 NEXT STEPS:"
echo ""
echo "1. Get your public URL from whichever tool you use"
echo "2. Go to: https://console.twilio.com/us1/develop/sms/settings/whatsapp-sandbox"
echo "3. Set 'When a message comes in' to:"
echo "   YOUR_PUBLIC_URL/api/whatsapp/webhook"
echo "   Method: POST"
echo "4. Click Save"
echo "5. Send a WhatsApp message to test!"
echo ""
echo "Your backend is running on port 5000 ✅"
